### ISSUE TITLE
Battle City Alpha english

### ISSUE THREAD

**Issue by salvadorc17** [Battle-City-Alpha/BattleCityAlpha-HubClient#1]
Hi, your project is really cool, but it does need English version, any way you can do it, or want help for do other languages?

**Comment by Tic-Tac-Toc** [comment]
Hello, the team of Battle City Alpha already thought of this issue and we decide that we don't want to have an english version and prefer to stay only in french. 
We don't want a huge community but a small community with good link between people. ;)

TTT.

**Comment by salvadorc17** [comment]
Can i have permission to do by myself. I dont understand english and liked so much game idea.

**Comment by Tic-Tac-Toc** [comment]
Yes you can if you want.

**Comment by salvadorc17** [comment]
Can i have source code for the client, so its easy to change all the text.

**Comment by Tic-Tac-Toc** [comment]
Sorry, the client source code isn't public for the first version of Battle City Alpha. 
You can use the same concept, but i will not give you the source code.
